install:
  - sudo apt-get update
  - sudo apt-get install libxml2-dev libreadline-dev augeas-lenses libaugeas-dev libaugeas-dev
language: ruby
bundler_args: --without development
script: "bundle install && bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.8.7
env:
  - PUPPET_GEM_VERSION="~> 2.7.0"
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email: false
